app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('orders.urls'))
]

app/cart/urls.py
from django.urls import path
from cart import views as v


app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', v.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', v.cart_remove, name='cart_remove'),
]

app/orders/urls.py
from django.urls import path
from orders import views as v


app_name = 'orders'

urlpatterns = [
    path('', v.order_prepare, name='order_prepare'),
    path('create/', v.order_create, name='order_create'),
    path('reset/', v.order_reset, name='order_reset'),
]

app/cart/models.py
from django.db import models

# Create your models here.

app/catalog/models.py
from django.db import models
from django.urls import reverse


class CategoryModel(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField(max_length=100, unique=True)

	class Meta:
		ordering = ['title']
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('catalog:products_by_category', args=[self.slug])


class ProductModel(models.Model):
	category = models.ForeignKey(CategoryModel, related_name='products', on_delete=models.PROTECT)
	title = models.CharField(max_length=100)
	slug = models.SlugField(max_length=100)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	stock = models.PositiveIntegerField()
	availible = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['title']
		verbose_name = 'Продукт'
		verbose_name_plural = 'Продукты'

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('catalog:product_detail', args=[self.id])

app/orders/models.py
from django.db import models
from catalog.models import ProductModel


class OrderModel(models.Model):
	first_name = models.CharField(max_length=50, verbose_name='Ваше Имя')
	last_name = models.CharField(max_length=50, verbose_name='Ваша Фамилия')
	email = models.EmailField(verbose_name='Ваш Email')
	address = models.CharField(max_length=250, verbose_name='Адрес')
	city = models.CharField(max_length=50, verbose_name='Город')
	comment = models.TextField(verbose_name='Комментарий')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ['-created']
		verbose_name = 'Заказ'
		verbose_name_plural = 'Заказы'

	def __str__(self):
		return 'Заказ номер - ' + str(self.id)


class OrderItemModel(models.Model):
	order = models.ForeignKey(OrderModel, related_name='items', on_delete=models.PROTECT)
	product = models.ForeignKey(ProductModel, related_name='order_items', on_delete=models.PROTECT)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)

	def __str__(self):
		return str(self.id)

	def get_cost(self):
		return self.price * self.quantity

app/cart/forms.py
from django import forms


PRODUCT_Q_CH = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
	# quantity = forms.TypedChoiceField(choices=PRODUCT_Q_CH, coerce=int)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

app/orders/forms.py
from django import forms
from orders.models import OrderModel


class OrderForm(forms.ModelForm):
	class Meta:
		model = OrderModel
		fields = ['first_name', 'last_name', 'email', 'city', 'address', 'comment']

app/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import ProductModel
from cart.cart import Cart
from cart.forms import CartAddProductForm
from django.contrib import messages


@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(ProductModel, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product, 1, cd['update'])
		messages.add_message(request, messages.SUCCESS, 'Услуга добавлена в заявку')
	return redirect('orders:order_prepare')


def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(ProductModel, id=product_id)
	cart.remove(product)
	messages.add_message(request, messages.SUCCESS, 'Услуга(и) удалена из заявки')
	return redirect('orders:order_prepare')

app/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from orders.models import OrderItemModel, OrderModel
from orders.forms import OrderForm
from cart.cart import Cart
from cart.forms import CartAddProductForm
from catalog.models import ProductModel
from django.contrib import messages
from django.db.models import F, Sum


def order_prepare(request):
	if request.session.get('order_created_id'):
		msg = 'Пожалуйста, сначала закончите с оформлением этой заявки! Либо отмените её - ссылка представлена ниже.'
		messages.add_message(request, messages.INFO, msg)
		return redirect('orders:order_create')
	products = ProductModel.objects.filter(availible=True)
	form = CartAddProductForm()

	data = {
		'products': products,
		'form': form
	}
	return render(request, 'catalog/list.html', data)


def order_create(request):
	if request.session.get('order_created_id'):
		# Вывести небольшой чек с данными из заказа
		# со ссылкой на оплату
		order_items = OrderItemModel.objects.filter(order_id=request.session.get('order_created_id'))
		total_price = sum(item['quantity'] * item['price'] for item in order_items.values('price', 'quantity'))
		order = get_object_or_404(OrderModel, id=request.session.get('order_created_id'))
		return render(request, 'orders/created.html', {'order_items': order_items, 'total_price': total_price, 'order': order})
	cart = Cart(request)
	if len(cart) == 0:
		msg = 'Ваша заявка пуста. Добавьте в неё услугу(и) для возможности перейти к шагу 2.'
		messages.add_message(request, messages.INFO, msg)
		return redirect('orders:order_prepare')

	form = OrderForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			order = form.save()
			for item in cart:
				OrderItemModel.objects.create(
					order=order,
					product=item['product'],
					quantity=item['quantity'],
					price=item['price']
				)
			request.session['order_created_id'] = order.id
			cart.clear()
			return redirect('orders:order_create')
	return render(request, 'orders/create.html', {'form': form})


def order_reset(request):
	if request.session.get('order_created_id'):
		del request.session['order_created_id']
		request.session.modified = True
		messages.add_message(request, messages.SUCCESS, 'Ваша заявка была сброшена.')
	return redirect('orders:order_prepare')

app/templates/base.html
{% load django_bootstrap5 %}
<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8" />
  <title>
    {% block title %}Не найдено{% endblock %}
  </title>
  <style type="text/css">
  </style>
</head>
<body>

  <div class="bg-secondary">
    <div class="container p-5 text-white text-center">
      <h3>[GK-RGB] ОНЛАЙН ЗАЯВКА НА УСЛУГИ</h3>
    </div>
  </div>

  <div class="bg-light">
    <div class="container p-3 text-primary">
      <ul class="nav nav-pills justify-content-center">
        <li class="nav-item">
          <a class="nav-link
          {% if request.resolver_match.view_name == 'orders:order_prepare' %} active {% endif %}" href="{% url 'orders:order_prepare' %}">Шаг 1. Выбор услуг</a>
        </li>
        <li class="nav-item">
          <a class="nav-link 
          {% if request.resolver_match.view_name == 'orders:order_create' %} active {% endif %}" href="{% url 'orders:order_create' %}">Шаг 2. Оформление заявки</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Шаг 3. Оплата</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Вернуться на сайт</a>
        </li>
      </ul>
    </div>
  </div>

<div class="container my-5">
  {% block content %}
  Не найдено
  {% endblock %}
</div>

  {% bootstrap_css %}
  {% bootstrap_javascript %}
</body>
</html>

app/templates/cart/detail.html
{% extends 'base.html' %}

{% block title %}
Ваша корзина
{% endblock %}

{% block content %}

Ваша корзина:<br /><br />

{% for item in cart %}

	{% with product=item.product %}
	<a href="{{product.get_absolute_url}}">Название товара: {{product.title}}</a><br />
	Количество: {{item.quantity}}<br />
	Стоимость: {{item.price}}<br />
	Сумма: {{item.total_price}}<br />
	<a href="{% url 'cart:cart_remove' product.id %}">Удалить из корзины</a><br /><br />
	{% endwith %}

{% endfor %}
<br />
Сумма: {{cart.get_total_price}}
<br />
<a href="{% url 'catalog:product_list' %}">Перейти в каталог</a> | 
<a href="{% url 'orders:order_create' %}">Оформить заказ</a>

{% endblock %}

app/templates/catalog/list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}

{% if not category %}Каталог товаров{% else %}Список товаров по категории - {{ category.title }}{% endif %}

{% endblock %}

{% block content %}
<div class="row">
	<div class="col">
		{% bootstrap_messages %}
		<p>Здесь вы можете оформить заявку на наши услуги онлайн. Для этого выберите необходимое количество, если требуется и нажмите добавить в заявку. В процессе оформления можно будет конкретизировать Ваши требования в форме, которая будет шаге непосредственного оформления заявки.</p>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="card">
			<div class="card-header text-center">
				Наши услуги
			</div>
			<div class="card-body">
				{% for product in products %}
				<p class="fw-bold">{{ product.title }}</p>
				<p>{{ product.description }}</p>
				<form action="{% url 'cart:cart_add' product.id %}" method='post'>
					{% bootstrap_form form %}
					{%csrf_token%}
					{% bootstrap_button button_type="submit" content="Добавить в заявку" %}
				</form>
				<hr>
				{% endfor %}
			</div>
		</div>
	</div>

	<div class="col">
		<div class="card">
			<div class="card-header text-center">
				Заявка
			</div>
			<div class="card-body">
				{% for item in cart %}

				{% with product=item.product %}
				<p class="fw-bold">{{product.title}}</p>
				<p>Количество: {{item.quantity}} - 
				Стоимость: {{item.price}} - 
				Сумма: {{item.total_price}}</p>
				<a href="{% url 'cart:cart_remove' product.id %}">Убрать из заявки</a>
				<hr>
				{% endwith %}

				{% endfor %}
			</div>
			<div class="card-footer text-body-secondary text-center">
				{% with total_items=cart|length %}
				{% if total_items > 0 %}
				Общая сумма: {{cart.get_total_price}} руб. -> <a href="{% url 'orders:order_create' %}">Оформить заказ</a>
				{% else %}
				Пусто. В заявке ничего нет. Добавьте услуги.
				{% endif %}
				{% endwith %}				
			</div>
		</div>
	</div>

</div>
{% endblock %}

app/templates/catalog/product_detail.html
{% extends 'base.html' %}

{% block title %}

{{ product.title }}

{% endblock %}

{% block content %}

<br />{{ product.title }}
<br />{{ product.description }}<br />
<br />$ {{ product.price }}
<br />{{ product.stock }}

<form action="{% url 'cart:cart_add' product.id %}" method='post'>
	{%csrf_token%}
	{{cart_product_form}}
	<input type="submit" value="В корзину">
</form>

{% endblock %}

app/templates/orders/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}
Формирование заказа
{% endblock %}

{% block content %}
<div class="row">
	<div class="col">
		<p>Здесь вы можете оформить заявку на наши услуги онлайн. Для этого выберите необходимое количество, если требуется и нажмите добавить в заявку. В процессе оформления можно будет конкретизировать Ваши требования в форме, которая будет шаге непосредственного оформления заявки.</p>
	</div>
</div>
<div class="row">
	<div class="col">
		<div class="card">
			<div class="card-header text-center">
				Проверьте Вашу заявку
			</div>
			<div class="card-body">
				{% for item in cart %}

				{% with product=item.product %}
				<p class="fw-bold">{{product.title}}</p>
				<p>Количество: {{item.quantity}} - 
				Стоимость: {{item.price}} - 
				Сумма: {{item.total_price}}</p>
				<hr>
				{% endwith %}

				{% endfor %}
			</div>
			<div class="card-footer text-body-secondary text-center">
				{% with total_items=cart|length %}
				{% if total_items > 0 %}
				Общая сумма: {{cart.get_total_price}} руб.
				{% else %}
				Пусто. В заявке ничего нет. Добавьте услуги.
				{% endif %}
				{% endwith %}				
			</div>
		</div>
	</div>
	<div class="col">
		<div class="card">
			<div class="card-header text-center">
				Заполните форму ниже
			</div>
			<div class="card-body">
				<form action="{% url 'orders:order_create' %}" method='post'>
					{% bootstrap_form form %}
					{% csrf_token %}
					{% bootstrap_button button_type="submit" content="Оформить заявку и перейти к оплате" %}
				</form>
			</div>
		</div>
	</div>

</div>
{% endblock %}

app/templates/orders/created.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}
Заказ успешно сформирован
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-7 mx-auto border p-3 rounded-3">
		{% bootstrap_messages %}
		<p>Заказ под номером "{{ request.session.order_created_id }}" создан. Его необходимо оплатить!</p>
		<p class="fw-bold">Детали Вашей заявки:</p>
		<ol>
			{% for item in order_items %}
			<li>{{item.product.title}} - кол-во: {{item.quantity}}; цена: {{item.price}} руб.; сумма: {{ item.get_cost }} руб.</li>
			{% endfor %}
		</ol>
		<p><span class="fw-bold">Итого к оплате:</span> {{ total_price }} руб.</p>
		<p>
			<a href="">Вы можете оплатить заказ</a> | <a href="{% url 'orders:order_reset' %}">Или отменить заказ</a>
		</p>
		<hr>
		<p class="fw-bold">Дополнительная информация:</p>
		<p>Заявитель: {{order.last_name}} {{order.first_name}}</p>
		<p>Адресс: {{ order.address }}</p>
		<p>Город: {{ order.city }}</p>
		<p>Email: {{ order.email }}</p>
		<p>Комментарий: {{ order.comment }}</p>
	</div>
</div>
{% endblock %}